### PR TITLE
Fix file handle leak in mmomni backup

### PR DESCRIPTION
**Pull request by naggie**
### Summary

When running `mmomni backup` I got this error:

```
ERROR: error adding data files to tarball: open /var/opt/mattermost/data/20211209/teams/noteam/channels/.../users/.../.../Image Pasted at 2021-12-9 19-50_thumb.jpg: too many open files

```
Looking at the code, `defer file.Close()` is used inside a loop. This results in all the file handles still being open until the loop terminates and the function returns; if you have many files in the database it's possible to exceed the OS limit.

This change closes the file handle within the loop, whilst retaining the `defer`ed close such that handles are always closed even on error.

I've tested this against my own server, and have validated that it fixes the problem whilst still producing a valid backup. I've also signed the CLA.

### CODE REVIEW

**Review by fmartingr — APPROVED** [review]
Hey @naggie , thanks for taking the time to submit a contribution! 👍 You solved the issue and closed the handlers more efficiently while maintaining the current logic, so this looks good to me.

**Comment by naggie** [comment]
No problem @fmartingr -- thanks for reviewing.

**Comment by phoinixgrr** [comment]
@mgdelacroix  Any objections merging this?

**Review by mgdelacroix — APPROVED** [review]
LGTM! :sparkles: Thanks @naggie!!

**Pull request merged**
